name: Trigger auto deployment for msdocscontainerappnewgithub

# When this action will be executed
on:
  # Automatically trigger it when detected changes in repo
  push:
    branches: 
      [ master ]
    paths:
    - '**'
    - '.github/workflows/msdocscontainerappnewgithub-AutoDeployTrigger-38121ae4-4f64-4852-8df3-f1f81bbec1cf.yml'

  # Allow mannually trigger 
  workflow_dispatch:      

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout to the branch
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Log in to container registry
        uses: docker/login-action@v1
        with:
          registry: acrmnbtut.azurecr.io
          username: ${{ secrets.MSDOCSCONTAINERAPPNEWGITHUB_REGISTRY_USERNAME }}
          password: ${{ secrets.MSDOCSCONTAINERAPPNEWGITHUB_REGISTRY_PASSWORD }}

      - name: Build and push container image to registry
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: acrmnbtut.azurecr.io/msdocscontainerappnewgithub:${{ github.sha }}
          file: ./Dockerfile
          context: ./


  deploy:
    runs-on: ubuntu-latest
    needs: build
    
    steps:
      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.MSDOCSCONTAINERAPPNEWGITHUB_AZURE_CREDENTIALS }}


      - name: Deploy to containerapp
        uses: azure/CLI@v1
        with:
          inlineScript: |
            az config set extension.use_dynamic_install=yes_without_prompt
            az containerapp registry set -n msdocscontainerappnewgithub -g my-container-apps --server acrmnbtut.azurecr.io --username  ${{ secrets.MSDOCSCONTAINERAPPNEWGITHUB_REGISTRY_USERNAME }} --password ${{ secrets.MSDOCSCONTAINERAPPNEWGITHUB_REGISTRY_PASSWORD }}
            az containerapp update -n msdocscontainerappnewgithub -g my-container-apps --image acrmnbtut.azurecr.io/msdocscontainerappnewgithub:${{ github.sha }}
